/**
 * TEMPORARY PLATFORM ADMIN DATA
 * Preview only — not production tenant truth.
 * Replace with /api/v1/admin/tenants, /billing, /audit, etc.
 */

import type {
  AdminAuditEvent,
  AdminBillingAlert,
  AdminComplianceItem,
  AdminMessageTemplate,
  AdminPlatformFlags,
  AdminTenant,
} from "@/types/admin";

export const ADMIN_NOTICE =
  "Platform admin console · Separate from tenant workspaces · Wire to /api/v1/admin when available";

export const ADMIN_PLATFORM_STATS = {
  tenants: 1284,
  active: 1198,
  suspended: 24,
  pastDue: 31,
  trial: 62,
  messages24h: 4_820_441,
  platformDeliveryRate: 98.41,
  mrr: 186420,
  openCompliance: 7,
};

export const ADMIN_TENANTS: AdminTenant[] = [
  {
    id: "ten_acme",
    organization: "Acme Commerce",
    slug: "acme-commerce",
    ownerEmail: "ops@acme.io",
    status: "active",
    planCode: "growth",
    planName: "Growth",
    createdAt: "2025-11-02T10:00:00Z",
    lastActiveAt: "2026-09-08T05:40:00Z",
    users: 14,
    domains: 3,
    messages30d: 182400,
    usagePct: 72,
    mrr: 249,
    bounceRate: 0.42,
    complaintRate: 0.01,
    risk: "low",
    sendingFrozen: false,
    features: { campaigns: true, webhooks: true, apiAccess: true, customDomains: true },
    limits: { messages: 250000, domains: 10, apiKeys: 20 },
  },
  {
    id: "ten_north",
    organization: "Northwind Labs",
    slug: "northwind-labs",
    ownerEmail: "billing@northwind.dev",
    status: "past_due",
    planCode: "scale",
    planName: "Scale",
    createdAt: "2024-06-18T08:00:00Z",
    lastActiveAt: "2026-09-07T22:10:00Z",
    users: 41,
    domains: 8,
    messages30d: 910200,
    usagePct: 91,
    mrr: 899,
    bounceRate: 0.88,
    complaintRate: 0.04,
    risk: "medium",
    notes: "Card declined twice. Dunning day 5.",
    sendingFrozen: false,
    features: { campaigns: true, webhooks: true, apiAccess: true, customDomains: true },
    limits: { messages: 1000000, domains: 25, apiKeys: 50 },
  },
  {
    id: "ten_orbit",
    organization: "Orbit Mail Co",
    slug: "orbit-mail",
    ownerEmail: "founder@orbitmail.test",
    status: "suspended",
    planCode: "starter",
    planName: "Starter",
    createdAt: "2026-01-14T12:00:00Z",
    lastActiveAt: "2026-08-29T16:00:00Z",
    users: 3,
    domains: 1,
    messages30d: 0,
    usagePct: 0,
    mrr: 0,
    bounceRate: 4.2,
    complaintRate: 0.6,
    risk: "high",
    notes: "Suspended for elevated complaints. Pending compliance review.",
    sendingFrozen: true,
    features: { campaigns: false, webhooks: false, apiAccess: false, customDomains: true },
    limits: { messages: 20000, domains: 2, apiKeys: 5 },
  },
  {
    id: "ten_pixel",
    organization: "PixelForge",
    slug: "pixelforge",
    ownerEmail: "hello@pixelforge.app",
    status: "trial",
    planCode: "growth",
    planName: "Growth (trial)",
    createdAt: "2026-09-01T09:00:00Z",
    lastActiveAt: "2026-09-08T04:00:00Z",
    users: 2,
    domains: 1,
    messages30d: 4200,
    usagePct: 8,
    mrr: 0,
    bounceRate: 0.2,
    complaintRate: 0,
    risk: "low",
    sendingFrozen: false,
    features: { campaigns: true, webhooks: true, apiAccess: true, customDomains: true },
    limits: { messages: 50000, domains: 5, apiKeys: 10 },
  },
  {
    id: "ten_harbor",
    organization: "Harbor Logistics",
    slug: "harbor-logistics",
    ownerEmail: "it@harbor.example",
    status: "sending_frozen",
    planCode: "growth",
    planName: "Growth",
    createdAt: "2025-03-22T11:00:00Z",
    lastActiveAt: "2026-09-08T01:20:00Z",
    users: 9,
    domains: 2,
    messages30d: 64000,
    usagePct: 64,
    mrr: 249,
    bounceRate: 2.1,
    complaintRate: 0.12,
    risk: "high",
    notes: "Sending frozen after spike in hard bounces. Login still allowed.",
    sendingFrozen: true,
    features: { campaigns: true, webhooks: true, apiAccess: true, customDomains: true },
    limits: { messages: 100000, domains: 5, apiKeys: 10 },
  },
  {
    id: "ten_delta",
    organization: "Delta Notify",
    slug: "delta-notify",
    ownerEmail: "admin@deltanotify.io",
    status: "active",
    planCode: "starter",
    planName: "Starter",
    createdAt: "2026-04-04T15:00:00Z",
    lastActiveAt: "2026-09-06T19:00:00Z",
    users: 5,
    domains: 2,
    messages30d: 18400,
    usagePct: 55,
    mrr: 49,
    bounceRate: 0.35,
    complaintRate: 0.02,
    risk: "low",
    sendingFrozen: false,
    features: { campaigns: false, webhooks: true, apiAccess: true, customDomains: true },
    limits: { messages: 30000, domains: 3, apiKeys: 5 },
  },
];

export const ADMIN_AUDIT: AdminAuditEvent[] = [
  {
    id: "aud_1",
    at: "2026-09-08T05:12:00Z",
    actor: "platform@texto.dev",
    action: "tenant.suspend",
    tenant: "Orbit Mail Co",
    detail: "Elevated complaint rate",
  },
  {
    id: "aud_2",
    at: "2026-09-08T04:40:00Z",
    actor: "platform@texto.dev",
    action: "billing.reminder_sent",
    tenant: "Northwind Labs",
    detail: "Payment reminder #2",
  },
  {
    id: "aud_3",
    at: "2026-09-07T21:05:00Z",
    actor: "platform@texto.dev",
    action: "sending.freeze",
    tenant: "Harbor Logistics",
    detail: "Hard bounce spike",
  },
  {
    id: "aud_4",
    at: "2026-09-07T18:22:00Z",
    actor: "platform@texto.dev",
    action: "quota.override",
    tenant: "Acme Commerce",
    detail: "Temporary +50k messages",
  },
  {
    id: "aud_5",
    at: "2026-09-07T12:01:00Z",
    actor: "platform@texto.dev",
    action: "api_keys.revoke_all",
    tenant: "Orbit Mail Co",
    detail: "Security incident response",
  },
];

export const ADMIN_BILLING_ALERTS: AdminBillingAlert[] = [
  {
    id: "bill_1",
    tenantId: "ten_north",
    organization: "Northwind Labs",
    kind: "past_due",
    amount: 899,
    daysOverdue: 5,
    message: "Invoice INV-2041 unpaid",
  },
  {
    id: "bill_2",
    tenantId: "ten_pixel",
    organization: "PixelForge",
    kind: "trial_ending",
    message: "Trial ends in 3 days",
  },
  {
    id: "bill_3",
    tenantId: "ten_harbor",
    organization: "Harbor Logistics",
    kind: "quota_exceeded",
    message: "Approaching message ceiling with frozen sending",
  },
];

export const ADMIN_COMPLIANCE: AdminComplianceItem[] = [
  {
    id: "cmp_1",
    tenantId: "ten_orbit",
    organization: "Orbit Mail Co",
    severity: "high",
    type: "spam_complaint",
    summary: "Complaint rate exceeded 0.3% over 7 days",
    createdAt: "2026-09-01T10:00:00Z",
    status: "investigating",
  },
  {
    id: "cmp_2",
    tenantId: "ten_harbor",
    organization: "Harbor Logistics",
    severity: "medium",
    type: "abuse_report",
    summary: "Recipient ISP flagged burst traffic",
    createdAt: "2026-09-07T20:00:00Z",
    status: "open",
  },
];

export const ADMIN_MESSAGE_TEMPLATES: AdminMessageTemplate[] = [
  {
    id: "tpl_pay",
    name: "Payment reminder",
    subject: "Action required: unpaid invoice for {{organization}}",
    body: "Your Texto subscription invoice is unpaid. Update payment to avoid service interruption.",
    channel: "billing",
  },
  {
    id: "tpl_suspend",
    name: "Suspension notice",
    subject: "Account suspended — {{organization}}",
    body: "Your workspace has been temporarily suspended. Contact support to restore access.",
    channel: "system",
  },
  {
    id: "tpl_freeze",
    name: "Sending frozen",
    subject: "Outbound sending paused for {{organization}}",
    body: "Sending is temporarily frozen while we review deliverability. Dashboard access remains available.",
    channel: "compliance",
  },
  {
    id: "tpl_quota",
    name: "Quota warning",
    subject: "You are approaching your message limit",
    body: "Your workspace has used most of this period’s message entitlement. Upgrade or wait for reset.",
    channel: "billing",
  },
];

export const ADMIN_PLATFORM_FLAGS: AdminPlatformFlags = {
  maintenanceMode: false,
  newSignups: true,
  globalSendThrottle: false,
  requireDnsVerified: true,
};

export function getAdminTenant(id: string) {
  return ADMIN_TENANTS.find((tenant) => tenant.id === id) ?? null;
}
