spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoint:
    health:
      show-details: always
      show-components: always

email-platform:
  security:
    api-docs-public: true
  billing:
    provider: noop
  ses:
    enabled: ${SES_ENABLED:false}
    region: ${SES_REGION:ap-south-1}
    configuration-set-name: ${SES_CONFIGURATION_SET_NAME:}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        environment: local
