spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

management:
  endpoint:
    health:
      show-details: never
      show-components: when-authorized

email-platform:
  security:
    api-docs-public: false
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  mailpit:
    host: ${MAILPIT_HOST}
    smtp-port: ${MAILPIT_SMTP_PORT}
  mta:
    implementation: ${MTA_IMPLEMENTATION}
    smtp:
      host: ${MTA_SMTP_HOST}
      port: ${MTA_SMTP_PORT}
      connection-timeout-ms: ${MTA_SMTP_CONNECTION_TIMEOUT_MS:5000}
      read-timeout-ms: ${MTA_SMTP_READ_TIMEOUT_MS:5000}
      write-timeout-ms: ${MTA_SMTP_WRITE_TIMEOUT_MS:5000}
      ehlo-hostname: ${MTA_SMTP_EHLO_HOSTNAME}
      starttls:
        enabled: ${MTA_SMTP_STARTTLS_ENABLED:true}
        required: ${MTA_SMTP_STARTTLS_REQUIRED:true}
      ssl:
        enabled: ${MTA_SMTP_SSL_ENABLED:false}

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        environment: prod
